### ISSUE TITLE
Simple documentation

### ISSUE THREAD

**Issue by KyleU** [outr/jefe#1]
I'm in dire need of a project like this, any chance you could write up some basic workflows for using jefe?

**Comment by darkfrog26** [comment]
Sorry, for some reason I never got a notification about this ticket. Can you clarify exactly what you're wanting to do?  Jefe does a LOT of things and is being used in production systems right now, but the documentation is nil.

**Comment by KyleU** [comment]
Just a paragraph or two talking about the use cases for Jefe, and  the workflow for getting an new client update packaged and deployed.

**Comment by darkfrog26** [comment]
Are you talking about just packing and deploying a client or a server?  It supports both, just trying to determine exactly what you're trying to accomplish.

**Comment by KyleU** [comment]
I build a few GUI and server apps for desktop installation, currently using sbt-assembly, sbt-native-packager, and Jsomething (forgot the name, not at my computer). All of them have slight issues, and none of them help with updating the software. Does Jefe compete with those plugins, or complement them?

**Comment by darkfrog26** [comment]
Server management with proxying is my main focus on Jefe right now, but it does offer some really interesting capabilities for GUI apps presuming that the JRE is installed on the machine.  I've actually started working on a prototype using Scala Native to download the JRE if it's not installed, but it's not ready yet.  That would give the capability of downloading a 50kb executable that downloads and installs everything it needs to run.

Take a look at the example: https://github.com/outr/jefe/blob/master/example/src/main/scala/com/outr/jefe/Test.scala

It's very simple, but it's a decent representation of launching a client application. It makes the presumption that all dependencies are accessible in Maven / Ivy repositories.

**Comment by darkfrog26** [comment]
@KyleU were you able to figure it out?

**Comment by KyleU** [comment]
I grabbed the example, and I've got a better idea of Jefe's purpose now. Thanks!
