### ISSUE TITLE
Use HTTPS for fetching from artifact servers

### ISSUE THREAD

**Issue by tharant** [outr/jefe#22]
Maven central, among others, now requires HTTPS but `jefe` appears to use HTTP resulting in errors fetching `jefe-boot` version info and thus a failure to start `jefe`.  

```bash
$ http get http://repo1.maven.org/maven2/com/outr/jefe-boot_2.12/maven-metadata.xml
HTTP/1.1 501 HTTPS Required
Accept-Ranges: bytes
Connection: close
Content-Length: 133
Content-Type: text/plain
Date: Thu, 16 Jan 2020 16:13:04 GMT
Server: Varnish
Via: 1.1 varnish
X-Cache: MISS
X-Cache-Hits: 0
X-Served-By: cache-jfk8138-JFK
X-Timer: S1579191185.533581,VS0,VE0

501 HTTPS Required.
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```

As a workaround, we're doing `sudo touch latest.version && sudo service jefe start` which appears to skip the new version check and thus allow `jefe` to start successfully.

More info at the links below:
https://links.sonatype.com/central/501-https-required

https://www.alphabot.com/security/blog/2020/java/Your-Java-builds-might-break-starting-January-13th.html

**Comment by darkfrog26** [comment]
I was able to reproduce this. A workaround for this is to create a copy of `latest.version` as `version` and it should always use that and stop even checking for a new version.

I'll update this ticket when I have a chance to fix this.

**Comment by darkfrog26** [comment]
Okay, `2.0.8` is released that should fully resolve this issue going forward.  I don't remember if you guys are using native or JAR version of `jefe-native`, but both are available here: https://github.com/outr/jefe/tree/master/bin

I personally recommend the JAR as `scala-native` seems to bring about its own pains.
